module PeakTracker
  class Client
    ##
    # Config for the PeakTracker GraphQL client.
    class Config
      attr_reader :host

      def initialize(host = "https://peak-tracker.com/gql")
        @host = host
      end

      def graphql_endpoint
        @graphql_endpoint ||= GraphQL::Client::HTTP.new(host)
      end

      # The file graphql.schema.json is generated with the command `yarn codegen`.
      def graphql_schema
        # This JSON parse and dump step here is necessary because the schema generated by GraphQL codegen
        # does not include the data key but starts right away with the __schema key, which
        # is probably the right way to do it, so we adjust it here to make it work with the Ruby
        # GraphQL client.
        @graphql_schema ||= { data: JSON.parse(File.read(graphql_schema_file_path)) }.to_json
      end

      def graphql_schema_file_path
        @graphql_schema_file_path ||= File.join(File.dirname(__FILE__), "../../../graphql.schema.json")
      end
    end
  end
end
